GET http://localhost:1234/beneficiary/get

####
POST http://localhost:1234/beneficiary/add
Content-Type: application/json

{
    #"beneficiaryId": 101,
    "accountNumber": 125120022,
    "beneficiaryName": "Roshini",
    "ifscCode": "84114Roshini",
    "accountId": 1
  }
####

PUT http://localhost:1234/beneficiary/update
Content-Type: application/json

{
    "beneficiaryId": 109,
    "accountNumber": 125120022,
    "beneficiaryName": "kani",
    "ifscCode": "84114Kani",
    "accountId": 1
  }

####
DELETE http://localhost:1234/beneficiary/202





###########################
GET http://localhost:1234/beneficiary/get

###
GET http://localhost:1234/beneficiary/byaccount/1
